### PR TITLE
Add mpeg_aac_decoder example

### PR DESCRIPTION
**Pull request by probablykasper**
Adds an example (as discussed in #42) which:
1. Reads aac content from an mpeg container
2. Decoding it to PCM using [fdk-aac crate](https://crates.io/crates/fdk-aac)
3. Plays it using [rodio](https://crates.io/crates/rodio)

### CODE REVIEW

**Comment by probablykasper** [comment]
Not sure why `alsa-sys` is failing to build, it works fine for me on macOS

**Comment by alfg** [comment]
Ah, seems like a platform specific thing. The `libasound2` is missing on the Travis build. I'll check into this.

**Comment by alfg** [comment]
Ok, I have an idea. Since this is a platform-specific example, can we wrap this into it's own crate within the examples directory? This way it can run separately from the other examples with its own dependencies and won't affect `cargo test` in the parent.

**Comment by probablykasper** [comment]
Made it into it's own package, and renamed the audio

**Comment by alfg** [comment]
Thanks!

**Pull request merged**
